version: "3"

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - .:/usr/app
    links:
      - mongo
      - redis
  
  mongo:
    container_name: mongoDB_dev
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: redis_dev
    image: redis
    ports:
      - "6379:6379"